SPK_NAME = mdbtools
SPK_VERS = 0.7.1
SPK_REV = 2
SPK_ICON = src/mdbtools.png

DEPENDS = cross/mdbtools07

MAINTAINER = SynoCommunity 
DESCRIPTION = MDB Tools - Read Access databases on *nix
RELOAD_UI = no
DISPLAY_NAME = MDB Tools 
STARTABLE = no
CHANGELOG = "Also use existing buffer when printing to stderr."

HOMEPAGE   = https://github.com/brianb/mdbtools
LICENSE    = 

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh
ADDITIONAL_SCRIPTS = 

INSTALL_PREFIX = /usr/local/$(SPK_NAME)

include ../../mk/spksrc.spk.mk
